-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 13:10:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProyecto`),
  UNIQUE INDEX `idProyecto_UNIQUE` (`idProyecto` ASC) VISIBLE,
  UNIQUE INDEX `nombreProyecto_UNIQUE` (`nombreProyecto` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `peso` INT NOT NULL,
  `nombreCliente` VARCHAR(20) NOT NULL,
  `idProyecto` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_proyecto_idx` (`idProyecto` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `mydb`.`proyecto` (`idProyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`requisito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`requisito` (
  `idRequisito` INT NOT NULL AUTO_INCREMENT,
  `esfuerzo` INT NULL DEFAULT NULL,
  `nombreRequisito` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idRequisito`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_has_requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_has_requisito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_has_requisito` (
  `Cliente_idCliente` INT NOT NULL,
  `Requisito_idRequisito` INT NOT NULL,
  `valor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Requisito_idRequisito`),
  INDEX `fk_Cliente_has_Requisito_Requisito1_idx` (`Requisito_idRequisito` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Requisito_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Requisito_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_has_Requisito_Requisito1`
    FOREIGN KEY (`Requisito_idRequisito`)
    REFERENCES `mydb`.`requisito` (`idRequisito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `nombreUsuario` VARCHAR(12) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Rol` ENUM('admin', 'user') NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto_has_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_has_usuario` (
  `idProyecto` INT NOT NULL,
  `nombreUsuario` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idProyecto`, `nombreUsuario`),
  INDEX `fk_usuario_idx` (`nombreUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `mydb`.`proyecto` (`idProyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `mydb`.`usuario` (`nombreUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`se_relacionan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`se_relacionan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`se_relacionan` (
  `Requisito_idRequisito1` INT NOT NULL,
  `Requisito_idRequisito2` INT NOT NULL,
  `tipoRelacion` ENUM('I', 'J', 'X') NULL DEFAULT NULL,
  PRIMARY KEY (`Requisito_idRequisito1`, `Requisito_idRequisito2`),
  INDEX `fk_Requisito_has_Requisito_Requisito2_idx` (`Requisito_idRequisito2` ASC) VISIBLE,
  INDEX `fk_Requisito_has_Requisito_Requisito1_idx` (`Requisito_idRequisito1` ASC) VISIBLE,
  CONSTRAINT `fk_Requisito_has_Requisito_Requisito1`
    FOREIGN KEY (`Requisito_idRequisito1`)
    REFERENCES `mydb`.`requisito` (`idRequisito`),
  CONSTRAINT `fk_Requisito_has_Requisito_Requisito2`
    FOREIGN KEY (`Requisito_idRequisito2`)
    REFERENCES `mydb`.`requisito` (`idRequisito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
